### ISSUE TITLE
Don't output object file unless there is no error during compilation

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#214] opened 2018-06-07 18:21 UTC
Apparently this issue title is a thing, and I'm running into it while attempting to compile things (specifically I'm starting to run into <string> problems instead of any other header(oops, spoke too soon, darn you <functional>! as well as "call of nonfunction in function" in <chrono>!), so at least it's now centralized... I hope... because there's too many errors...)

But yhea if occ runs into a compilation error a blank file will be produced, meaning omake thinks that it's actually existing and therefore treats it as if it was a correctly output file the next time around.

**Comment by GitMensch** [comment] 2018-06-07 19:17
I think the way to do this with less overhead as possible: create all intermediate files using a temporary base name (GnuCOBOL uses PID + counter) and move the requested files to the real name when finished without an error (otherwise, if possible [wouldn't be for hard errors like "Access Violation" in occ delete them]).
If you do it this way (instead of using a temporary folder) you save the i/o overhead that may occur when the move will be done between different harddrives/mounts.

If you want to do it very clean (even in the case of a hard chrash of the compiler): add a new internal-only option that is only set within the compiler and duplicate the processes:

process 1 - takes all command line parsing internally calculate the temporary file name
process 2 (on "good" implementations use the quick `fork()`, otherwise start a new process passing the "internal mode" option and the temporary names) - does the actual compilation
process 1 uses `waitpid()`[possibly with a time-out to optional kill process2], waits for process2 to finish and depending on its return code either delete the temporary files or renames them to the target name.

**Comment by LADSoft** [comment] 2018-06-08 01:38
yeah i forgot about the output file issue when implementing bug fixes last night.   Will fix over the weekend :)

**Comment by LADSoft** [comment] 2018-06-09 03:11
I took your first example; also intercepted SIGSEGV and SIGINT to clean up.

**Comment by chuggafan** [comment] 2018-06-09 16:15
Problem seems to still appear when I take the master branch and rebase it on your new work. It is output into the build directory (and no temp file(?), go figure!) Thankfully I partially got \<string\> to stop being a problem child in the meantime by downgrading it back, but.... yhea...

**Comment by LADSoft** [comment] 2018-06-11 01:48
when i tested this I tried three things...   first I created a file that had enough errors to get the 'too many errors' message.    Then I created a file with just a handful of errors.   Then I injected some code into the compiler to make it crash.   I also debugged the compiler to make sure it was generating the correct temporary files.   In all cases it *seemed* to clean up properly.    The only caveat being that as per a previous issue written last year, if the output file already exists the previously existing version will persist through the process if a new file can't be written.   Which means if you didn't delete the previously (bad) version it would persist until such a time as you either deleted or have a successful compile.

I'm wondering what I'm missing?

**Comment by chuggafan** [comment] 2018-06-11 02:12
I re-found it when attempting to build on my broken master branch, I know that the previous object file was not there (I had to manually delete it) but it continuously popped up, I think this issue may now have something to do with OMake but I highly doubt that in the slightest, I'll do some future testing tomorrow, as I am going to sleep atm.

**Comment by LADSoft** [comment] 2018-06-12 02:20
I'll look for this while I'm testing for the crashes...

**Comment by LADSoft** [comment] 2018-06-17 06:53
i looked into this some more.   There were issues while the compiler was crashing but I can't duplicate them now that it isn't.

**Comment by GitMensch** [comment] 2018-06-17 19:28
The configure script of MPIR 3.0.0 leaves a "dummy-$PID.o". Is this something that needs to be fixed on the OrangeC side?

Note: the script was run with `../configure "CC=occ --nologo" "MAKE=omake -w" "LD=olink --nologo" "CPP=ocpp --nologo" "CXX=occ --nologo" "CXXCPP=ocpp --nologo" "GREP=ogrep" "EGREP=ogrep" "NM=onm --nologo" --with-yasm=/d/dev/yasm/yasm-1.3.0-win32.exe --enable-gmpcompat --disable-static --enable-shared "CPP_FOR_BUILD=ocpp --nologo" CC_FOR_BUILD="occ --nologo" AR="olib --nologo"`, just in case you want to reproduce it.

**Comment by LADSoft** [comment] 2018-06-28 03:50
i haven't really had a chance to look up mpir 3.0.0...  but orange c doesn't delete .o files when they are used as intermediates...   so...

**Comment by LADSoft** [comment] 2018-06-28 03:50
chuggafan,   i've been noticing there may be a problem if you hit ctrl-c during a compile...   are you still having other problems as well?

**Comment by chuggafan** [comment] 2018-06-28 13:01
Hmm, it seems that if occ errors it drops out a .oo file these days and it is never cleaned up, but I haven't tested if it still breaks in my Master branch (the one I'm using for the upgrading of the library), mostly because I have had other stuff I've been working on.

**Comment by GitMensch** [comment] 2018-06-29 19:14
@LADSoft wrote

> i haven't really had a chance to look up mpir 3.0.0...

Currently won't configure because of missing support for `.align`, see #236

**Comment by chuggafan** [comment] 2018-06-29 19:34
? is that relevant to this issue

**Comment by GitMensch** [comment] 2018-06-29 19:37
I guess so. @LADSoft referenced mpir, likely because I've found different dummy-*pid*.o (and dummy-*pid*.rel) files staying there.

But I've just rechecked: these actually stay there when the configure script is run and therefore doing this provides a testbed for this.

**Comment by GitMensch** [comment] 2018-06-29 22:00
Just to explicit ask this: should the .rel files stay or should they automatically be removed?

**Comment by LADSoft** [comment] 2018-06-30 03:35
the .rel files should be automatically removed.   I had commented out the 'unlink' line though for testing and never added it back...   will revert it soon...

**Comment by GitMensch** [comment] 2018-06-30 06:21
Thank you for the clarification. I'll just ignore it for now and report it as bug when I see them in the future.

Note: I suggest to add an option like --save-temps to leave the rel (and other possible files) in place. This way the default is the unlink but you can always get an intermediate file if needed, even in release versions.

That is what the GnuCOBOL project does and it has been proven quite useful...

**Comment by chuggafan** [comment] 2018-06-30 23:11
This issue now appears to be fixed, I will reopen it if I run into it again though, thanks!

**Comment by chuggafan** [comment] 2018-06-30 23:20
Ah no, I just discovered that the problem had moved, it still exists whenever I attempt to compiler up the newer libcxx on my master branch, the problem had just moved into a different folder *shrug*

**Closed** 2018-07-01 00:05 UTC

**Comment by LADSoft** [comment] 2018-07-01 00:08
I actually looked at this today...   there was a problem with the '.oo' files not getting deleted properly which i've fixed.   Are there still other problems?
