### ISSUE TITLE
An interesting project to stress the compiler

### ISSUE THREAD

**Issue by bencz** [LADSoft/OrangeC#469] opened 2019-12-06 10:53 UTC
A LINQ implementation in C: https://github.com/haifenghuang/linq4c

**Comment by GitMensch** [comment] 2019-12-06 13:03
There are a lot of interesting things, for example at some point we should try [building LibreOffice](https://wiki.documentfoundation.org/Development/BuildingOnWindows) and if it compiles check if it somehow actually works... but I definitely don't volunteer for this.

What are your current results with the interesting project you've suggested?

**Comment by AlexN-114** [comment] 2019-12-09 08:30
[WinVI](http://winvi.de/en/) is my favorite test.

**Comment by GitMensch** [comment] 2019-12-09 14:25
@AlexN-114 and what is your test result?

**Comment by LADSoft** [comment] 2019-12-11 13:45
I used to compile WINVI as part of the tests....    then I would load it up and type in it a bit.  worked pretty well except I always have trouble remembering how to exit lol!.   I still have a copy around somewhere...

@AlexN-114 I looked briefly at this in between testing occil and it seems like it needs some linux component for GC.  I dunno if it would work on mingw or not...   sigh...

**Comment by AlexN-114** [comment] 2019-12-11 14:29
I tried to compile it with Orange C. 
I found, that ...
  ... the structure OPENFILENAMEW is missing (but you can use the structure OPENFILENAME).
  ... you have to change L"" to L"\0". Without this patch WinVI shows in the title not the file name but chinese signs. For me it looks like, that the empty string is not generated correct in any case. But I couldn't produce this beheaviour it in a small example.
  ... only the Debug runs correct. The Release version doesn't start.
  ... the IDE (later than 6.0.41.1) crashes very often with this project.
  ... CC386 has less problems with it.
It runs well and without patches with MinGW(-W64)-GCC and Pelles C

**Comment by chuggafan** [comment] 2019-12-11 15:31
Yhea, looks like much of the unicode support in the old lib that's being used is just... not there. At one point I tried to make a project that would copy/paste definitions from MSDN to file headers but that never particularly panned out.... The closest you can get to accurate recreations of the windows file headers now are in MINGW64, which is a weird mess of copyright that a lawyer would have to verify at this point due to how weird it is, so uh.... yhea that's a thing.

**Comment by LADSoft** [comment] 2019-12-11 19:16
@chuggafan There is rudimentary support even though a lot is missing.   But you could say that about windows prototypes in general with this library...   If I remember correctly,  the biggest problem with what support is there is there for unicode is you can't compile both ASCII and UNICODE at the same time.   This because the selection or prototype and structure declaration is done via #define.    Instead of defining separate 'A' and 'W' versions like most runtimes do.

@AlexN-114 I will look again at winvi...   but it is possible I've broken stuff since last time I compiled it.   I do know I recently ran into a bug that I had introduced which may be related to the L'\0' thing....   that may be on the 'split' branch I'll have to check.    As far as openfilew, I've been avoiding adding 'W' versions of things to the RTL since it doesn't really support them, so I may have added it to the VI sources directly.

**Comment by chuggafan** [comment] 2019-12-11 19:19
Yhea, the problem is that it doesn't support both ASCII and UNICODE at the same time, but there are some structs that are very different that just don't exist there and are incorrectly defined because they don't have separate A and W versions. So that's a big problem, to be honest, if really needed, we could require that MSVC be installed with C++ support and search the locations of the headers from MSVC beforehand, but that'd not work for EXTREMELY old platforms... so there's a lot to unpack there...

**Comment by GitMensch** [comment] 2019-12-11 19:29
> to be honest, if really needed, we could require that MSVC be installed with C++ support and search the locations of the headers from MSVC beforehand

You are kidding, aren't you?

One of the main points of this GPLed compiler and runtime is to not use the proprietary (multi-gigabyte only online-installable) compiler at all! If you are not kidding I have to absolutely disagree with you on this point.

**Comment by LADSoft** [comment] 2019-12-11 19:38
I have to agree with @GitMensch here and for two reasons : one if I have to install MSVC to begin with I might as well use it rather than play with OCC and two it might not be as easy as it seems to parse all the microsoft-specific stuff that is likely to be found in those headers...

**Comment by chuggafan** [comment] 2019-12-11 19:41
I can understand that idea, what I meant to say was that I'd prefer if we piggyback off of someone else's work in this case, and if we can't use MINGW, microsoft's headers would be the next best bet, MINGW though, being LGPL, should be sufficient. After all, it's all either public domain, LGPL, or that weird MINGW license. 

Maintaining an accurate recreation of Microsoft's headers is a herculean task, last year I tried to automatically generate a ton of the headers off of Microsoft's docs (with actual, small success), but the effort in putting it all together and gathering the information is something a team of hundreds need to put significant time into to get anywhere done with.

**Comment by GitMensch** [comment] 2019-12-11 19:47
+1 for mingw

**Comment by LADSoft** [comment] 2019-12-12 15:21
yeah i agree, don't really want to be maintaining an entirely different set of windows api documents. 

@chuggafan why do you think the legalites of using mingw64 version are so problematic?

**Comment by chuggafan** [comment] 2019-12-12 15:27
Because MINGW64 has such a mixture of LGPL and public domain source code, and IIRC unless the people that statically link to the headers they must post the source code due to LGPL requirements unless there's an exception (IIRC GLIBC specifically has this exception to allow for companies to link to it otherwise literally no one would use GLIBC). And I'm not sure if there's a 3rd license hidden there or not, so I'd have to check all of mingw64, or someone could specifically ask them if there'd be any problems encountered by using them here... of which I have too much other work at the moment to figure out how to communicate with them to do so.

**Comment by GitMensch** [comment] 2019-12-12 16:39
You can link LGPLed code against anything and only have to provide code for the LGPL parts of you both change and distribute binaries of those.
At least from your post I see no issue so far

**Comment by LADSoft** [comment] 2019-12-12 17:50
I thought the rule for LGPL was you had to distribute your code in binary (object code) format so the end user can link against any version of the LGPL code he wants?   But that you aren't necessarily forced to give out your *own* source code?   But I'm surprised the MINGW team would force their users to do that either...

**Comment by GitMensch** [comment] 2019-12-12 18:40
The FSF had good information on this license and linking.

**Comment by LADSoft** [comment] 2019-12-27 23:47
as far as the WINVI goes, the good news is that while I was working on debugging #297 I found several reasons that the IDE would crash and fixed them.    The bad news is that while my version of WINVI compiles, it doesn't currently run properly.

**Comment by AlexN-114** [comment] 2020-01-05 11:23
> The bad news is that while my version of WINVI compiles, it doesn't currently run properly.
For me only the Debug-version runs properly and it is hard to debug the Release version.

**Comment by LADSoft** [comment] 2020-01-05 22:20
I did fix the problem at some point - there was an issue in the people analyzer when optimizing constants.   Unfortunately I think I fixed it on the 'split' branch.    Hopefully we can get that merged back in in the near future...

**Comment by LADSoft** [comment] 2020-01-09 19:58
I opened issue #478 to track the issue with WINVI not running...

**Comment by LADSoft** [comment] 2023-06-25 00:13
we eventually switched to the PELLES C windows headers, which should be much better at unicode support.    Since we have a separate issue #478 for winvi I will close this.

**Closed by LADSoft** 2023-06-25 00:13 UTC
Labels: good first issue
