### ISSUE TITLE
Make OrangeC a 64 bit compiler

### ISSUE THREAD

**Issue by 3oheicrw** [LADSoft/OrangeC#681] opened 2022-07-23 01:56 UTC
I know it's not easy. But what's the point of a 32 bit only compiler nowadays? Going 64 bit will very much help adoption of OrangeC.

**Comment by chuggafan** [comment] 2022-07-23 02:06
Duplicate of #495 

It's been on the radar for years, it's just there's so much stuff to clear out of the way first (such as getting first class C++ support) and stuff like speeding up the compiler by a few orders of magnitudes (GCC, the big lug, is faster at compilation of sqlite3.c) that it isn't super high on the priority list, and even getting the compiler to compile itself as 64-bit is more difficult now than it was a few years ago (some thanks to the change I suggested for front/middle/backend having 32-bit pointers passed through the system instead of pointers of platform size...).

Work has been slowly progressing on this though! Oasm got support in 2019 for (most of) x64 assembly in order to use SSE instructions for floating point, and there's plans for even different architectures entirely. Most of this is hobby projects, so if you want to help develop this you can, there's tons of open issues.

**Comment by LADSoft** [comment] 2022-07-23 05:55
yeah there are only two people working on this and it is kind of a part time thing.   We welcome help if anyone is interested in working on one part or another...

**Closed** 2022-07-24 14:13 UTC
