### ISSUE TITLE
Build error with MSVC++

### ISSUE THREAD

**Issue by bencz** [LADSoft/OrangeC#281] opened 2018-11-15 18:40 UTC
Hi David!

I'm getting a error when I do a omake fullbuild

```
        omake -Clscrtl
        orc -i\src\clibs\stdinc -i\src\clibs\platform\win32\wininc lscrtl.rc
orc Version 6.0.36.1 Copyright (C) LADSoft 2006-2018
Error lscrtl.rc(34): Could not open windows.h for input
Error lscrtl.rc(35): Constant value expected

Error makefile(57): commands returned error code 1
        omake -Cpels
        olib -! C:\orangec\src\clibs\object\startup\lscrtl.l +- .\c0lsstartup.o C:\orangec\src\clibs\object\clib\srproc.o C:\orangec\src\clibs\object\windows\dllmain.o

Error makefile(38): commands returned error code 2
        omake -CDOS32 --eval="OBJECT=C:\orangec\src\clibs\object\dos"
        omake -Cle
        omake -Cpm
        olink -c+ -! /T:REAL -oC:\orangec\src\clibs\object\startup\pmstb .\pmstb.o .\pmode.o
        omake -Cdebug
        omake -Crtl
        omake -CCIL32
        omake -Crtl

Error makefile(28): commands returned error code 2

Error makefile(105): commands returned error code 2

Error makefile(85): commands returned error code 2
```

**Comment by LADSoft** [comment] 2018-11-16 00:31
hi alexandre,

it appears the problem is that ORANGEC is not defined.   It took a couple of builds to get the programs to all define it (when it isn't defined already) and it looks like that wasn't complete until 6.0.37.   If you want to use that version try defining it (to c:\orangec) otherwise upgrading should help.

**Comment by GitMensch** [comment] 2018-11-17 13:34
... so: can we close the issue?

**Closed** 2018-11-17 23:18 UTC
