### ISSUE TITLE
How to use the dependency generation feature of `occ` on makefile?

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#903] opened 2023-07-10 20:17 UTC
I only discovered this feature recently. I didn't know GCC also had a similar feature. Indeed, I don't know if such a feature exists at all. I have never written a makefile myself, even though I have edited other people's makefiles at various times to build their software. I rely entirely on IDEs like RedPanda DevCpp to build my programs. I think after I discover this feature, I will try to learn how to write a makefile. Please give me an example makefile that uses this feature. Thank you.

By the way, please give me a makefile that works with both omake and GNU make. Omake, IMO, is very unreliable software. Sometimes, omake crashes for no reason. The only thing I could see was a useless stack trace.

**Comment by GitMensch** [comment] 2023-07-10 20:26
> Sometimes, omake crashes for no reason. The only thing I could see was a useless stack trace.

If it crash, then please create an issue with the complete output and ideally (a link to) the Makefile (or just attach after renaming it to .txt). In the past nearly all hard crashes of any OrangeC tools got resolved in a very short amount of time!

**Comment by LADSoft** [comment] 2023-07-10 20:39
yeah i'm very interested in crashes.    Last time someone told me it crashed I worked on it for days but couldn't reproduce...   any information you can give would be good.   as far as omake not always working when it doesn't crash, thanks to your previous efforts we have #858 now which gives an indication of why complex makefiles don't always work...   this *may* be an indication of a more general problem.   It is high on my list...

Basically all those switches do is make a snippet of a make file that you include into another make file.   The snippet becomes useful because it informs the make program as to the fact that if you change a file included via the #include directive, here are the C/C++ files that are affected by that change.   It kinda automates a part of building make files that is not too glamourous when you decide to maintain something like that by hand...

I will make a short example in a little while...

**Comment by iahunq** [comment] 2023-07-10 21:19
> yeah i'm very interested in crashes. Last time someone told me it crashed I worked on it for days but couldn't reproduce... any information you can give would be good. as far as omake not always working when it doesn't crash, thanks to your previous efforts we have #858 now which gives an indication of why complex makefiles don't always work... this _may_ be an indication of a more general problem. It is high on my list...

You only tested with DEBUG on, didn't you? I found something really strange. If I use the MSVC WITH PDB build from CI then `omake` doesn't crash. But if I use the MSVC THEN WITH STATIC LIBRARY build or the MINGW64 THEN WITH STATIC LIBRARY build, it crashes.

**Comment by LADSoft** [comment] 2023-07-10 22:45
I usually cover my bases and turn off debug, if I can't get an immediate crash...

I made an example and in the process fixed a bug, so you'll need the compiler out of smoke test #20 or build your own...

for this example I took the 'lame' project out of the tests directory.

here it is: 
[lame.zip](https://github.com/LADSoft/OrangeC/files/12009044/lame.zip)

in the makefile I added a rule to make a file 'stubs.mak' buy using /MM on all the C files in this project.   you can do:

```
omake stub.mak
```

to create it.

if you look it it you can see it has the structure of a piece of a simple makefile.

the makefile in this directory will also use stub.mak if you tell it to:

```
omake STUB=YES
```

so type 'omake' once to get the project built, and again to show that it isn't going to build anything else (it will just run some tests)

after that modify 'fft.h' and type 

```
omake STUB=YES
```

and you will see it compiling just a couple of the files.

you can do that again if you want to prove it is done...

then modify 'lame.h' then

```
omake STUB=YES
```
again and you will see it chooses several files to recompile

the STUB=YES is only needed because in this simple example I don't include stub.mak unless you define STUB...   a more complete make program would probably go through some hoops to get around needing it...

**Comment by LADSoft** [comment] 2023-07-10 22:48
7z muffed up the zip file, try this instead:
[lame.zip](https://github.com/LADSoft/OrangeC/files/12009119/lame.zip)

**Comment by LADSoft** [comment] 2023-07-10 23:11
ok so i thought about this:

```
But if I use the MSVC THEN WITH STATIC LIBRARY build or the MINGW64 THEN WITH STATIC LIBRARY build, it crashes.
```

and this doesn't happen for me, or even on appveyor...   the main builds on appveyor mostly build occ with one of the other compilers (msvc or clang or mingw64) and then build the compiler again with the binaries generated there (including the omake), which is enough to make the final OCC binaries.   However, rather than stop there we use those binaries (including the omake) to regenerate the binaries one more time, then as a final check on all those builds we compare the last two sets of binaries byte by byte and the builds don't succeed if they don't match.

If it passes all that then it goes on to build a bunch of C and C++ test programs and test their output....

anyway, the fact that omake works in all those scenarios, on appveyor, shows that your guess that there is some compatibility problem with windows 8.1 is right.

Likely there is some mismatch with the windows api between the compiler versions used to compile omake, and the windows 8.1.    Common problems would include occ using an api that isn't existant there; occ setting WINVER too high; or worst case the compiler runtime itself might be using some API that doesn't work...

**Closed** 2023-07-14 02:24 UTC
