### ISSUE TITLE
Use `omake` to build FOX Toolkit

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#922] opened 2023-07-14 11:57 UTC
This is about testing `omake`, not about actually building FOX Toolkit like #770

This is what I see when I run `omake`:

```
$ omake
Making all in utils
        g++ -DPACKAGE_NAME=\"fox\" -DPACKAGE_TARNAME=\"fox\" -DPACKAGE_VERSION=\"1.7.84\" -DPACKAGE_STRING=\"fox\ 1.7.84\" -DPACKAGE_BUGREPORT=\"jeroen@fox-toolkit.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"fox\" -DVERSION=\"1.7.84\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DLT_OBJDIR=\".libs/\" -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DX_DISPLAY_MISSING=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_DIRENT_H=1 -DHAVE_LIBPTHREAD=1 -DHAVE_PTHREAD_GETNAME_NP=1 -DHAVE_PTHREAD_SETNAME_NP=1 -DHAVE_SEMAPHORE_H=1 -DHAVE_IMMINTRIN_H=1 -DHAVE_PNG_H=1 -DHAVE_TIFF_H=1 -DHAVE_ZLIB_H=1 -DHAVE_BZLIB_H=1 -I. -I/usr/include/freetype2 -Wall -Wextra -Woverloaded-virtual -Wshadow -Wstrict-overflow -Wstrict-aliasing -Wdouble-promotion -Wno-implicit-fallthrough -DHAVE_JPEG_H=1 -DHAVE_PNG_H=1 -DHAVE_TIFF_H=1 -DHAVE_ZLIB_H=1 -DHAVE_BZ2LIB_H=1 -DNO_XIM -DHAVE_XFT_H=1 -DHAVE_GL_H=1 -DHAVE_GLU_H=1 -MT reswrap.o -MD -MP -MF .deps/reswrap.Tpo -c -o reswrap.o reswrap.cpp
<command-line>: warning: missing terminating " character
g++: warning: 1.7.84": linker input file unused because linking not done
g++: error: 1.7.84": linker input file not found: Invalid argument
        mv -f .deps/reswrap.Tpo .deps/reswrap.Po

Error makefile(440): commands returned error code 1

Error makefile(496): commands returned error code 1
```

**Comment by LADSoft** [comment] 2023-07-14 17:49
as we found in #860 the problem is this:

```
-DPACKAGE_STRING=\"fox\ 1.7.84\"
```

specifically, '\ ' 

Windows compilers such as clang, msvc, mingw64 don't support it the way gcc does on linux.

At some cost to backwards compatability of make files, I fixed orange c to support it in #860, but the caveat is that to support it, orange C has to be compiled with another compiler that supports it.   Since the other windows compilers don't support it, compiling orange c with one of them will result in it not being supported.

The CI builds of orange C on appveyor build orange C with itself, so it should be supported there.

**Comment by LADSoft** [comment] 2023-07-14 17:50
duplicate of #860

**Closed by LADSoft** 2023-07-14 17:50 UTC

**Comment by iahunq** [comment] 2023-07-14 19:13
@LADSoft This issue is about testing `omake`. #860 is about `gccocc` to test the compatibility of GCC and binutils emulators with the configure script. With this issue you could see I'm using `g++` as the compiler.

**Comment by iahunq** [comment] 2023-07-14 19:19
> Windows compilers such as clang, msvc, mingw64 don't support it the way gcc does on linux.

Are you really sure about this? Both GCC and Clang work as expected. They have no problems with these options passed to them.

**Comment by iahunq** [comment] 2023-07-14 19:26
Update: It seems this is not a problem of `omake` at all. `mingw32-make` has the very same issue:

```
$ mingw32-make -j4
Making all in utils
mingw32-make[1]: Entering directory 'C:/msys64/home/Administrator/fox-1.7.84/utils'
g++ -DPACKAGE_NAME=\"fox\" -DPACKAGE_TARNAME=\"fox\" -DPACKAGE_VERSION=\"1.7.84\" -DPACKAGE_STRING=\"fox\ 1.7.84\" -DPACKAGE_BUGREPORT=\"jeroen@fox-toolkit.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"fox\" -DVERSION=\"1.7.84\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DLT_OBJDIR=\".libs/\" -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DX_DISPLAY_MISSING=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_DIRENT_H=1 -DHAVE_LIBPTHREAD=1 -DHAVE_PTHREAD_GETNAME_NP=1 -DHAVE_PTHREAD_SETNAME_NP=1 -DHAVE_SEMAPHORE_H=1 -DHAVE_IMMINTRIN_H=1 -DHAVE_PNG_H=1 -DHAVE_TIFF_H=1 -DHAVE_ZLIB_H=1 -DHAVE_BZLIB_H=1 -I.   -I/usr/include/freetype2  -Wall -Wextra -Woverloaded-virtual -Wshadow -Wstrict-overflow -Wstrict-aliasing -Wdouble-promotion -Wno-implicit-fallthrough -DHAVE_JPEG_H=1 -DHAVE_PNG_H=1 -DHAVE_TIFF_H=1 -DHAVE_ZLIB_H=1 -DHAVE_BZ2LIB_H=1 -DNO_XIM -DHAVE_XFT_H=1 -DHAVE_GL_H=1 -DHAVE_GLU_H=1 -MT reswrap.o -MD -MP -MF .deps/reswrap.Tpo -c -o reswrap.o reswrap.cpp
mv -f .deps/reswrap.Tpo .deps/reswrap.Po
C:/msys64/usr/bin/sh.exe ../libtool  --tag=CXX   --mode=link g++  -Wall -Wextra -Woverloaded-virtual -Wshadow -Wstrict-overflow -Wstrict-aliasing -Wdouble-promotion -Wno-implicit-fallthrough -DHAVE_JPEG_H=1 -DHAVE_PNG_H=1 -DHAVE_TIFF_H=1 -DHAVE_ZLIB_H=1 -DHAVE_BZ2LIB_H=1 -DNO_XIM -DHAVE_XFT_H=1 -DHAVE_GL_H=1 -DHAVE_GLU_H=1   -o reswrap.exe reswrap.o
libtool: link: g++ -Wall -Wextra -Woverloaded-virtual -Wshadow -Wstrict-overflow -Wstrict-aliasing -Wdouble-promotion -Wno-implicit-fallthrough -DHAVE_JPEG_H=1 -DHAVE_PNG_H=1 -DHAVE_TIFF_H=1 -DHAVE_ZLIB_H=1 -DHAVE_BZ2LIB_H=1 -DNO_XIM -DHAVE_XFT_H=1 -DHAVE_GL_H=1 -DHAVE_GLU_H=1 -o .libs/reswrap.exe reswrap.o
mingw32-make[1]: Leaving directory 'C:/msys64/home/Administrator/fox-1.7.84/utils'
Making all in include
mingw32-make[1]: Entering directory 'C:/msys64/home/Administrator/fox-1.7.84/include'
mingw32-make[1]: Nothing to be done for 'all'.
mingw32-make[1]: Leaving directory 'C:/msys64/home/Administrator/fox-1.7.84/include'
Making all in lib
mingw32-make[1]: Entering directory 'C:/msys64/home/Administrator/fox-1.7.84/lib'
C:/msys64/mingw64/bin/mingw32-make.exe  all-am
mingw32-make[2]: Entering directory 'C:/msys64/home/Administrator/fox-1.7.84/lib'
C:/msys64/usr/bin/sh.exe ../libtool  --tag=CXX   --mode=compile g++ -DPACKAGE_NAME=\"fox\" -DPACKAGE_TARNAME=\"fox\" -DPACKAGE_VERSION=\"1.7.84\" -DPACKAGE_STRING=\"fox\ 1.7.84\" -DPACKAGE_BUGREPORT=\"jeroen@fox-toolkit.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"fox\" -DVERSION=\"1.7.84\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DLT_OBJDIR=\".libs/\" -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DX_DISPLAY_MISSING=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_DIRENT_H=1 -DHAVE_LIBPTHREAD=1 -DHAVE_PTHREAD_GETNAME_NP=1 -DHAVE_PTHREAD_SETNAME_NP=1 -DHAVE_SEMAPHORE_H=1 -DHAVE_IMMINTRIN_H=1 -DHAVE_PNG_H=1 -DHAVE_TIFF_H=1 -DHAVE_ZLIB_H=1 -DHAVE_BZLIB_H=1 -I. -I../include -I../include  -I/usr/include/freetype2 -DFOXDLL -DFOXDLL_EXPORTS -DWIN32 -DNDEBUG -D_WINDOWS -DUNICODE -D_USRDLL -D_CRT_SECURE_NO_WARNINGS -Wall -Wextra -Woverloaded-virtual -Wshadow -Wstrict-overflow -Wstrict-aliasing -Wdouble-promotion -Wno-implicit-fallthrough -DHAVE_JPEG_H=1 -DHAVE_PNG_H=1 -DHAVE_TIFF_H=1 -DHAVE_ZLIB_H=1 -DHAVE_BZ2LIB_H=1 -DNO_XIM -DHAVE_XFT_H=1 -DHAVE_GL_H=1 -DHAVE_GLU_H=1 -MT FX88591Codec.lo -MD -MP -MF .deps/FX88591Codec.Tpo -c -o FX88591Codec.lo FX88591Codec.cpp
C:/msys64/usr/bin/sh.exe ../libtool  --tag=CXX   --mode=compile g++ -DPACKAGE_NAME=\"fox\" -DPACKAGE_TARNAME=\"fox\" -DPACKAGE_VERSION=\"1.7.84\" -DPACKAGE_STRING=\"fox\ 1.7.84\" -DPACKAGE_BUGREPORT=\"jeroen@fox-toolkit.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"fox\" -DVERSION=\"1.7.84\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DLT_OBJDIR=\".libs/\" -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DX_DISPLAY_MISSING=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_DIRENT_H=1 -DHAVE_LIBPTHREAD=1 -DHAVE_PTHREAD_GETNAME_NP=1 -DHAVE_PTHREAD_SETNAME_NP=1 -DHAVE_SEMAPHORE_H=1 -DHAVE_IMMINTRIN_H=1 -DHAVE_PNG_H=1 -DHAVE_TIFF_H=1 -DHAVE_ZLIB_H=1 -DHAVE_BZLIB_H=1 -I. -I../include -I../include  -I/usr/include/freetype2 -DFOXDLL -DFOXDLL_EXPORTS -DWIN32 -DNDEBUG -D_WINDOWS -DUNICODE -D_USRDLL -D_CRT_SECURE_NO_WARNINGS -Wall -Wextra -Woverloaded-virtual -Wshadow -Wstrict-overflow -Wstrict-aliasing -Wdouble-promotion -Wno-implicit-fallthrough -DHAVE_JPEG_H=1 -DHAVE_PNG_H=1 -DHAVE_TIFF_H=1 -DHAVE_ZLIB_H=1 -DHAVE_BZ2LIB_H=1 -DNO_XIM -DHAVE_XFT_H=1 -DHAVE_GL_H=1 -DHAVE_GLU_H=1 -MT FX88592Codec.lo -MD -MP -MF .deps/FX88592Codec.Tpo -c -o FX88592Codec.lo FX88592Codec.cpp
C:/msys64/usr/bin/sh.exe ../libtool  --tag=CXX   --mode=compile g++ -DPACKAGE_NAME=\"fox\" -DPACKAGE_TARNAME=\"fox\" -DPACKAGE_VERSION=\"1.7.84\" -DPACKAGE_STRING=\"fox\ 1.7.84\" -DPACKAGE_BUGREPORT=\"jeroen@fox-toolkit.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"fox\" -DVERSION=\"1.7.84\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DLT_OBJDIR=\".libs/\" -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DX_DISPLAY_MISSING=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_DIRENT_H=1 -DHAVE_LIBPTHREAD=1 -DHAVE_PTHREAD_GETNAME_NP=1 -DHAVE_PTHREAD_SETNAME_NP=1 -DHAVE_SEMAPHORE_H=1 -DHAVE_IMMINTRIN_H=1 -DHAVE_PNG_H=1 -DHAVE_TIFF_H=1 -DHAVE_ZLIB_H=1 -DHAVE_BZLIB_H=1 -I. -I../include -I../include  -I/usr/include/freetype2 -DFOXDLL -DFOXDLL_EXPORTS -DWIN32 -DNDEBUG -D_WINDOWS -DUNICODE -D_USRDLL -D_CRT_SECURE_NO_WARNINGS -Wall -Wextra -Woverloaded-virtual -Wshadow -Wstrict-overflow -Wstrict-aliasing -Wdouble-promotion -Wno-implicit-fallthrough -DHAVE_JPEG_H=1 -DHAVE_PNG_H=1 -DHAVE_TIFF_H=1 -DHAVE_ZLIB_H=1 -DHAVE_BZ2LIB_H=1 -DNO_XIM -DHAVE_XFT_H=1 -DHAVE_GL_H=1 -DHAVE_GLU_H=1 -MT FX88593Codec.lo -MD -MP -MF .deps/FX88593Codec.Tpo -c -o FX88593Codec.lo FX88593Codec.cpp
C:/msys64/usr/bin/sh.exe ../libtool  --tag=CXX   --mode=compile g++ -DPACKAGE_NAME=\"fox\" -DPACKAGE_TARNAME=\"fox\" -DPACKAGE_VERSION=\"1.7.84\" -DPACKAGE_STRING=\"fox\ 1.7.84\" -DPACKAGE_BUGREPORT=\"jeroen@fox-toolkit.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"fox\" -DVERSION=\"1.7.84\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DLT_OBJDIR=\".libs/\" -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DX_DISPLAY_MISSING=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_DIRENT_H=1 -DHAVE_LIBPTHREAD=1 -DHAVE_PTHREAD_GETNAME_NP=1 -DHAVE_PTHREAD_SETNAME_NP=1 -DHAVE_SEMAPHORE_H=1 -DHAVE_IMMINTRIN_H=1 -DHAVE_PNG_H=1 -DHAVE_TIFF_H=1 -DHAVE_ZLIB_H=1 -DHAVE_BZLIB_H=1 -I. -I../include -I../include  -I/usr/include/freetype2 -DFOXDLL -DFOXDLL_EXPORTS -DWIN32 -DNDEBUG -D_WINDOWS -DUNICODE -D_USRDLL -D_CRT_SECURE_NO_WARNINGS -Wall -Wextra -Woverloaded-virtual -Wshadow -Wstrict-overflow -Wstrict-aliasing -Wdouble-promotion -Wno-implicit-fallthrough -DHAVE_JPEG_H=1 -DHAVE_PNG_H=1 -DHAVE_TIFF_H=1 -DHAVE_ZLIB_H=1 -DHAVE_BZ2LIB_H=1 -DNO_XIM -DHAVE_XFT_H=1 -DHAVE_GL_H=1 -DHAVE_GLU_H=1 -MT FX88594Codec.lo -MD -MP -MF .deps/FX88594Codec.Tpo -c -o FX88594Codec.lo FX88594Codec.cpp
XFX88593Codec.Tpo -c -o FX88593Codec.lo FX88593Codec.lo
XFX88592Codec.Tpo -c -o FX88592Codec.lo FX88592Codec.lo
XFX88591Codec.Tpo -c -o FX88591Codec.lo FX88591Codec.lo
XFX88594Codec.Tpo -c -o FX88594Codec.lo FX88594Codec.lo
libtool: warning: libobj name 'FX88591Codec.Tpo -c -o FX88591Codec.lo FX88591Codec.lo' may not contain shell special characters.
libtool: warning: libobj name 'FX88592Codec.Tpo -c -o FX88592Codec.lo FX88592Codec.lo' may not contain shell special characters.
libtool: warning: libobj name 'FX88594Codec.Tpo -c -o FX88594Codec.lo FX88594Codec.lo' may not contain shell special characters.
libtool: warning: libobj name 'FX88593Codec.Tpo -c -o FX88593Codec.lo FX88593Codec.lo' may not contain shell special characters.
rm: unknown option -- crm
: unknown option -- c
rm: unknown option -- c
rm: unknown option -- c
Try 'rm --help' for more information.
Try 'rm --help' for more information.
Try 'rm --help' for more information.
Try 'rm --help' for more information.
libtool: compile:  g++ "-DPACKAGE_NAME=\\fox\" -DPACKAGE_TARNAME=\"fox\" -DPACKAGE_VERSION=\"1.7.84\" -DPACKAGE_STRING=\\fox 1.7.84\"" "-DPACKAGE_BUGREPORT=\\jeroen@fox-toolkit.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"fox\" -DVERSION=\"1.7.84\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DLT_OBJDIR=\".libs/\" -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DX_DISPLAY_MISSING=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_DIRENT_H=1 -DHAVE_LIBPTHREAD=1 -DHAVE_PTHREAD_GETNAME_NP=1 -DHAVE_PTHREAD_SETNAME_NP=1 -DHAVE_SEMAPHORE_H=1 -DHAVE_IMMINTRIN_H=1 -DHAVE_PNG_H=1 -DHAVE_TIFF_H=1 -DHAVE_ZLIB_H=1 -DHAVE_BZLIB_H=1 -I. -I../include -I../include -I/usr/include/freetype2 -DFOXDLL -DFOXDLL_EXPORTS -DWIN32 -DNDEBUG -D_WINDOWS -DUNICODE -D_USRDLL -D_CRT_SECURE_NO_WARNINGS -Wall -Wextra -Woverloaded-virtual -Wshadow -Wstrict-overflow -Wstrict-aliasing -Wdouble-promotion -Wno-implicit-fallthrough -DHAVE_JPEG_H=1 -DHAVE_PNG_H=1 -DHAVE_TIFF_H=1 -DHAVE_ZLIB_H=1 -DHAVE_BZ2LIB_H=1 -DNO_XIM -DHAVE_XFT_H=1 -DHAVE_GL_H=1 -DHAVE_GLU_H=1 -MT FX88591Codec.lo -MD -MP -MF .deps/FX88591Codec.Tpo -c -o FX88591Codec.lo FX88591Codec.cpp"  -DDLL_EXPORT -DPIC -o .libs/FX88591Codec.Tpo -c -o FX88591Codec.lo FX88591Codec.o
libtool: compile:  g++ "-DPACKAGE_NAME=\\fox\" -DPACKAGE_TARNAME=\"fox\" -DPACKAGE_VERSION=\"1.7.84\" -DPACKAGE_STRING=\\fox 1.7.84\"" "-DPACKAGE_BUGREPORT=\\jeroen@fox-toolkit.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"fox\" -DVERSION=\"1.7.84\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DLT_OBJDIR=\".libs/\" -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DX_DISPLAY_MISSING=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_DIRENT_H=1 -DHAVE_LIBPTHREAD=1 -DHAVE_PTHREAD_GETNAME_NP=1 -DHAVE_PTHREAD_SETNAME_NP=1 -DHAVE_SEMAPHORE_H=1 -DHAVE_IMMINTRIN_H=1 -DHAVE_PNG_H=1 -DHAVE_TIFF_H=1 -DHAVE_ZLIB_H=1 -DHAVE_BZLIB_H=1 -I. -I../include -I../include -I/usr/include/freetype2 -DFOXDLL -DFOXDLL_EXPORTS -DWIN32 -DNDEBUG -D_WINDOWS -DUNICODE -D_USRDLL -D_CRT_SECURE_NO_WARNINGS -Wall -Wextra -Woverloaded-virtual -Wshadow -Wstrict-overflow -Wstrict-aliasing -Wdouble-promotion -Wno-implicit-fallthrough -DHAVE_JPEG_H=1 -DHAVE_PNG_H=1 -DHAVE_TIFF_H=1 -DHAVE_ZLIB_H=1 -DHAVE_BZ2LIB_H=1 -DNO_XIM -DHAVE_XFT_H=1 -DHAVE_GL_H=1 -DHAVE_GLU_H=1 -MT FX88594Codec.lo -MD -MP -MF .deps/FX88594Codec.Tpo -c -o FX88594Codec.lo FX88594Codec.cpp"  -DDLL_EXPORT -DPIC -o .libs/FX88594Codec.Tpo -c -o FX88594Codec.lo FX88594Codec.o
libtool: compile:  g++ "-DPACKAGE_NAME=\\fox\" -DPACKAGE_TARNAME=\"fox\" -DPACKAGE_VERSION=\"1.7.84\" -DPACKAGE_STRING=\\fox 1.7.84\"" "-DPACKAGE_BUGREPORT=\\jeroen@fox-toolkit.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"fox\" -DVERSION=\"1.7.84\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DLT_OBJDIR=\".libs/\" -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DX_DISPLAY_MISSING=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_DIRENT_H=1 -DHAVE_LIBPTHREAD=1 -DHAVE_PTHREAD_GETNAME_NP=1 -DHAVE_PTHREAD_SETNAME_NP=1 -DHAVE_SEMAPHORE_H=1 -DHAVE_IMMINTRIN_H=1 -DHAVE_PNG_H=1 -DHAVE_TIFF_H=1 -DHAVE_ZLIB_H=1 -DHAVE_BZLIB_H=1 -I. -I../include -I../include -I/usr/include/freetype2 -DFOXDLL -DFOXDLL_EXPORTS -DWIN32 -DNDEBUG -D_WINDOWS -DUNICODE -D_USRDLL -D_CRT_SECURE_NO_WARNINGS -Wall -Wextra -Woverloaded-virtual -Wshadow -Wstrict-overflow -Wstrict-aliasing -Wdouble-promotion -Wno-implicit-fallthrough -DHAVE_JPEG_H=1 -DHAVE_PNG_H=1 -DHAVE_TIFF_H=1 -DHAVE_ZLIB_H=1 -DHAVE_BZ2LIB_H=1 -DNO_XIM -DHAVE_XFT_H=1 -DHAVE_GL_H=1 -DHAVE_GLU_H=1 -MT FX88592Codec.lo -MD -MP -MF .deps/FX88592Codec.Tpo -c -o FX88592Codec.lo FX88592Codec.cpp"  -DDLL_EXPORT -DPIC -o .libs/FX88592Codec.Tpo -c -o FX88592Codec.lo FX88592Codec.o
libtool: compile:  g++ "-DPACKAGE_NAME=\\fox\" -DPACKAGE_TARNAME=\"fox\" -DPACKAGE_VERSION=\"1.7.84\" -DPACKAGE_STRING=\\fox 1.7.84\"" "-DPACKAGE_BUGREPORT=\\jeroen@fox-toolkit.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"fox\" -DVERSION=\"1.7.84\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DLT_OBJDIR=\".libs/\" -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DX_DISPLAY_MISSING=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_DIRENT_H=1 -DHAVE_LIBPTHREAD=1 -DHAVE_PTHREAD_GETNAME_NP=1 -DHAVE_PTHREAD_SETNAME_NP=1 -DHAVE_SEMAPHORE_H=1 -DHAVE_IMMINTRIN_H=1 -DHAVE_PNG_H=1 -DHAVE_TIFF_H=1 -DHAVE_ZLIB_H=1 -DHAVE_BZLIB_H=1 -I. -I../include -I../include -I/usr/include/freetype2 -DFOXDLL -DFOXDLL_EXPORTS -DWIN32 -DNDEBUG -D_WINDOWS -DUNICODE -D_USRDLL -D_CRT_SECURE_NO_WARNINGS -Wall -Wextra -Woverloaded-virtual -Wshadow -Wstrict-overflow -Wstrict-aliasing -Wdouble-promotion -Wno-implicit-fallthrough -DHAVE_JPEG_H=1 -DHAVE_PNG_H=1 -DHAVE_TIFF_H=1 -DHAVE_ZLIB_H=1 -DHAVE_BZ2LIB_H=1 -DNO_XIM -DHAVE_XFT_H=1 -DHAVE_GL_H=1 -DHAVE_GLU_H=1 -MT FX88593Codec.lo -MD -MP -MF .deps/FX88593Codec.Tpo -c -o FX88593Codec.lo FX88593Codec.cpp"  -DDLL_EXPORT -DPIC -o .libs/FX88593Codec.Tpo -c -o FX88593Codec.lo FX88593Codec.o
g++.exe: warning: FX88594Codec.o: linker input file unused because linking not done
g++.exe: warning: FX88591Codec.o: linker input file unused because linking not done
g++.exe: error: FX88594Codec.o: linker input file not found: No such file or directory
g++.exe: error: FX88591Codec.o: linker input file not found: No such file or directory
g++.exe: warning: FX88592Codec.o: linker input file unused because linking not done
g++.exe: error: FX88592Codec.o: linker input file not found: No such file or directory
g++.exe: warning: FX88593Codec.o: linker input file unused because linking not done
g++.exe: error: FX88593Codec.o: linker input file not found: No such file or directory
mingw32-make[2]: *** [Makefile:1476: FX88592Codec.lo] Error 1
mingw32-make[2]: *** Waiting for unfinished jobs....
mingw32-make[2]: *** [Makefile:1476: FX88594Codec.lo] Error 1
mingw32-make[2]: *** [Makefile:1476: FX88593Codec.lo] Error 1
mingw32-make[2]: *** [Makefile:1476: FX88591Codec.lo] Error 1
mingw32-make[2]: Leaving directory 'C:/msys64/home/Administrator/fox-1.7.84/lib'
mingw32-make[1]: *** [Makefile:999: all] Error 2
mingw32-make[1]: Leaving directory 'C:/msys64/home/Administrator/fox-1.7.84/lib'
mingw32-make: *** [Makefile:496: all-recursive] Error 1
```

Only the POSIX GNU make `/usr/bin/make` works.
