### ISSUE TITLE
Fixing the reporting error to microsoft window

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#161] opened 2018-05-23 15:45 UTC
Whenever the compiler finds an error windows thinks the compiler has crashed, this is an issue in general because it's extremely detrimental to have to close two windows every time you try to recompile the program, this issue pops up on Windows 10 latest, at least on my machine

**Comment by LADSoft** [comment] 2018-05-24 08:21
are you using the IDE or compiling from the command line?   Which version of the compiler are you using, the one compiled with itself or the one compiled with one of the other compilers?   If the latter, which compiler?

Is the code you are compiling C code or C++ code?   What exactly is logged in the window as the failing file, 'occ.exe' or 'occpr.exe'?

Thanks!

**Comment by LADSoft** [comment] 2018-05-24 17:30
I'm not immediately seeing it...   would it be possible for you to share any modified sources?

**Comment by LADSoft** [comment] 2018-05-24 18:18
ok i see it now.   This is the first thing on my list :)

**Comment by GitMensch** [comment] 2018-05-24 19:42
Note: as long as the OrangeC parts were compiled with cl.exe and "/EHsc /RTc /RTCsu" they likely will show an helpful message in these places. As the binary compiled with "cl.exe" is primarily intended to recompile itself I'd favor "all checks" about performance in this case. Just an idea...

**Comment by chuggafan** [comment] 2018-05-25 02:42
Yhea, it appears this more has to do with something related to microsoft's compiler, still, this is an extremely annoying thing to run into when you're trying to recompile the compiler for testing purposes.

**Comment by GitMensch** [comment] 2018-05-25 06:48
> it appears this more has to do with something related to microsoft's compiler

I don't think so. Adding the mentioned compiler flags to invocations of cl.exe would should access to invalid and unlikely correct data.
Is there any difference when you build OrangeC and its RTL with these flags and try to rebuild it afterwards with itself?

**Comment by LADSoft** [comment] 2018-05-25 11:38
I don't know if this will help the present issue...   but an uncaught throw would cause windows to display one of those dialogs instead of terminating as per spec.   I've put up a new version to fix this.

**Comment by LADSoft** [comment] 2018-05-25 13:01
there was an additional problem with omake not quitting on time...

**Comment by GitMensch** [comment] 2018-05-25 21:59
@LADSoft 
I'm not sure if you consider this one fixed, I'm getting the same (for ocide.exe) when debugging :-(  (using current CI build)

**Comment by LADSoft** [comment] 2018-05-29 04:15
Is this still an issue?   If so I may need help isolating it...   I'll think up some questions to ask.

**Comment by chuggafan** [comment] 2018-05-29 04:17
It seems to have disappeared for me, but @GitMensch might be able to reproduce it, if he no longer can I'll just close this.

**Comment by GitMensch** [comment] 2018-05-29 12:58
I can reproduce this issue in ocide.exe when trying to debug in an environment where one of the dependency dll's are missing (which is the reason that the executable to debug can not start and the debugger obvious has nothing to attach to):

~~~
---------------------------
Access Violation
---------------------------

Access Violation:(C:\dev\orangec\bin\ocide.exe)
CS:EIP 0023:00455055  SS:ESP 002B:0019F61C
EAX: 00000000  EBX: 00454D46  ECX: 00000033  EDX: 00000000  flags: 00010246
EBP: 0019F70C  ESI: 00000000  EDI: 00595B94
 DS:     002B   ES:     002B   FS:     0053   GS:     002B

---------------------------
OK   
---------------------------
~~~

output of the module loader:

~~~

**Comment by GitMensch** [comment] 2018-05-29 21:10
Can be closed, I could reproduce the windows error message some days ago but now the most I can reproduce is an access violation.
Please close this issue.

**Closed** 2018-05-29 21:34 UTC
