### ISSUE TITLE
omake FR: add option to control that a rule does not exceed a given time limit

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#272] opened 2018-11-11 13:13 UTC
... and add this to the Makefiles used in CI, especially the regression tests.

I'm not aware of any option like this in other make implementations but *guess* that it may not be hard to implement as omake is the controlling process already.

Background is the hanging process when compiled with `+v` reported with #159, which brought the possibility of "process takes much to much time" or even "hangs" to my attention. Neither on a local build nor in a CI environment you'd like to have a single process taking an hour...

**Comment by LADSoft** [comment] 2018-12-08 21:58
the root cause of this issue is that built in timeouts in omake were not being handled properly.   I've fixed that in an upcoming push but am not sure whether we really need a specific per-rule timeout?

**Comment by GitMensch** [comment] 2018-12-08 22:41
> am not sure whether we really need a specific per-rule timeout

This depends on what you build and how the timeouts are calculated. For example if you build GCC 8 on an old machine this may take some hours from a single `make [all]` command... For anything we currently build in CI I *think* doesn't need 10 minutes therefore this seems a reasonable timeout there, but not for other projects/environments (so: we don#t need a specific "per-rule" timeout, but it would be nice to be able to have in the documentation where the timeouts apply and how they are adjustable.

**Comment by LADSoft** [comment] 2018-12-10 01:50
well i have to think about how real it is...   the problem with the CI build wasn't that the spawned process hung, it was that several instances of omake waited on a semaphore for other instances of omake to end and the timeout was very long.   I've addressed that by not having it wait and also lowering the timeout.

The timeout doesn't start until omake has finished processing all the rules so really the only issue at this point is that of what happens if a compiler or other tool gets into an infinite loop and just sits there...

**Comment by GitMensch** [comment] 2019-02-05 09:08
I wonder what the status of this issue is. Isn't this fixed already (without a command line option, if I remember correctly).

**Comment by LADSoft** [comment] 2019-02-06 13:39
yeah i fixed it but then i thought i saw it recur.    But haven't seen it in a  while so am going to close this unless it does recur again.

**Closed by LADSoft** 2019-02-06 13:39 UTC
