### ISSUE TITLE
editor behaviour

### ISSUE THREAD

**Issue by AlexN-114** [LADSoft/OrangeC#83] opened 2018-04-25 12:02 UTC
If I enter a '**{**' anywhere in the source code, it get always inputted at the start of the file.

**Comment by LADSoft** [comment] 2018-04-25 21:12
I'm not seeing it immediately.   What is the file extension of the file?   And what is the locale your computer is set to?

Thanks

**Comment by AlexN-114** [comment] 2018-04-26 09:25
I tried it again with Windows 7 - 64Bit.
When I use my default German keyboard layout (for '{' I have to use AltGr-7), it works like described before. When I switch to an English keyboard layout, it works correct. 
If you want, I can try it at the evening with Windows 10.
PS: It was a simple "hello.c".

**Comment by LADSoft** [comment] 2018-04-27 21:02
Sorry for not getting back sooner.

Yeah the german keyboard is known to cause issues for OCIDE, especially that particular key.   I haven't been able to directly test it because I don't have the hardware...   I will look at it again and see if I've introduced some issue since last time I worked on it.

**Comment by AlexN-114** [comment] 2018-04-28 08:43
I have tried it with Window 10 and it is the same like with Win 7. I saw this weird behavior is also with '['  (AltGr-8).
I assume, you need not a german keyboard. I think its enough, if you install a german keyboard driver. This is the reason, why I wrote which keys you have to press on a german keyboard.

**Comment by LADSoft** [comment] 2018-04-29 21:38
there was actually a function assigned to the ALT-BRACE button for US keyboards...   It went looking for a brace...   inserting one and looking for one at the same time is an undefined behavior :).   It has been fixed so that that functionality now requires the SHIFT key in addition to the ALT key, which I would expect to restore the brace to working properly for you.   please let me know if there are still problems and if so I will get a german keyboard driver and go deeper into any issues.

**Comment by GitMensch** [comment] 2018-05-07 12:42
I can reproduce the issue with most current CI build, this issue should be re-opened.

Steps to reproduce:

* press [WIN] + search for "languages"
* add language "German (Germany)" with keyboard German/Deutsch QWERTZ if missing
* ensure that the current keyboard (can be seen in the system tray) is set to this
* open editor in OCIDE, go to line 5 col 4
* press [AltGr] (or right [ALT]) + [8] (not on the numpad)

result: editor is positioned at line 1 col 1 and `[` entered
expected result:  `[` entered at current position

**Comment by LADSoft** [comment] 2018-05-08 22:40
thank you for the detailed instructions.   I am looking at this next...

**Comment by LADSoft** [comment] 2018-05-09 21:07
this should work now...

**Comment by GitMensch** [comment] 2018-05-30 10:15
Just hit this one again :-(
Happens when pressing [AltGr] (or right [ALT]) + [1] to [AltGr] + [7] (not on the numpad)

**Comment by LADSoft** [comment] 2018-06-01 02:04
Are those actually german characters as well?   Reason I'm asking is that the root cause of this problem is conflicting requirements...  those ALT0-ALT9 are basically used to jump to points in the source code which have been 'marked' through a similar key sequence.    There was no mark established so it defaults to the beginning of the file.   Because some of the alt keys generated characters both behaviors got triggered, and the result was a character at the beginning of file.

There was no way to distinguish between RIGHT-ALT and GR so there are specific exceptions for specific key sequences...   I took out four 'ASCII' characters associated with this discussion.   Are there other characters I need to take into account?

**Comment by GitMensch** [comment] 2018-06-01 22:22
The characters that are there in the "common" German keyboard layout are: 2=², 3=³, 7={, 8=[, 9=], 0=}

> There was no mark established so it defaults to the beginning of the file. 

In general it would be much less confusing (and conflicting) if "no mark established" would lead to "no re-position done. FR, wink, wink :-)

**Closed** 2018-06-05 03:08 UTC
