### ISSUE TITLE
[Feature request] Generating IL that can be recompiled back after being decompiler to C# by DotPeek

### ISSUE THREAD

**Issue by claunia** [LADSoft/OrangeC#510] opened 2020-05-20 00:36 UTC
I don't know if it can be done easily, but, well, it would make it effectively a good, and free, C to C# converter.

**Comment by chuggafan** [comment] 2020-05-20 02:34
This is quite literally impossible because of how C++/CLI works. A lot of C constructs don't exist in C#, you might get bindings or some attempts at generators, but a full *TRANSPILER* is a lot of effort for minimalistic gains in this area.

**Comment by bencz** [comment] 2020-05-20 02:35
Just generate the DLL or EXE using the occil and use a .net decompiler to generate the C# code...

https://www.jetbrains.com/decompiler/

**Comment by chuggafan** [comment] 2020-05-20 02:38
That only works if the entire output is managed code instead of mixed-managed code, which is an entirely possible thing that can happen. I don't think jet-brains works if it's mixed-managed.

**Comment by claunia** [comment] 2020-05-20 02:38
@chuggafan this has NOTHING to do with C++/CLI. This is a C compiler that generates IL and assembles PURE .NET, there's not mixed-managed here (besides P/Invokes but those are managed).

@bencz there are IL constructs that are not legal C#, and while jetbrains happily give you C# for it, you cannot compile it back

**Comment by chuggafan** [comment] 2020-05-20 02:47
Well, why not put in the work to get the C# to be re-compilable? Effectively would be the same thing, and remaking the compiler into a (decent) transpiler is an *incredible* amount of work because you'd have to change the frontend, middle-end, and backend all of which would have to be modified to effectively produce C# code. 

Is there anything that's reasonable within the scope of the current compiler to achieve this or would be effective in helping us reach this feature easier? This would also require a lot of help because there's effectively 1 person (I barely contribute atm) doing all of the work on this.  Even though I love to program in C# I don't see how this fits in with the already large list of milestones that exist or any of the "theoretical" goals of this compiler set.

**Comment by claunia** [comment] 2020-05-20 04:01
well you say put the work to get the C# to be recompilable to which I ask why not put a flag to emit only IL that is legal C#? There's already a flag to encase it into a class.

And this wouldn't require rewriting the whole compiler, that's like saying changing a compiler to stop emitting i686 instructions and emit only i586 requires rewriting the whole compiler. And this is not true.

As to how it fits, there is a lot of old C code, and newer C code, that doesn't have a proper C# equivalent, cannot be easily ported (coz preprocessor mostly), and cannot be just P/Invoked as some environments do not allow this (like webassembly).

**Comment by LADSoft** [comment] 2020-05-20 12:34
while I agree with you @claunia it could be done with a rewrite to the backend (or perhaps an entirely new backend dedicated to this purpose) and maybe some minor alterations to the front end to pass the names of enumerations through,  I also think this is kinda beyond the scope of what I'm trying to do here;   also even though I might do it anyway there is a lot of work piled up ahead of it, currently I have five milestones planned and none of them are trivial to do.    The results might also be sub-optimal, a single file with an entire program, possibly expressions being done naively (as I don't know how much effort it would be to take the expressions as found in the backend and make complicated statements out of them), a lot of pinvoke declarations for msvcrt.dll, and so forth.   Also strings in C can not be considered the same as strings in C# because they have to be available to the C runtime, so there would have to be some way to allow for that.   Right now the IL just makes byte arrays for them but it might get trickier to do it right for pure C# code...

While it could be done, I just don't have the time at the moment to do it...

**Comment by GitMensch** [comment] 2020-05-20 12:47
@LADSoft What do you agree to?

@claunia  said one thing I agree that _may_ be relative trivial and then useful to be able to later do post-processing outside of OrangeC:

> put a flag to emit only IL that is legal C#

Is this possible?

**Comment by claunia** [comment] 2020-05-20 12:56
@LADSoft I am not in any hurry

About strings, P/Invoke has a way to automarshal strings to char*. The problem is detecting where char* IS a string and where it is a byte array. Easiest way, just let the user fix that.

In my opinion, if the IL can be passed to a decompiler, pasted as C#, and compiled again, most of the work is done, and whatever is left to fix manually is still a very minor fraction of what manual code conversion supposes.

Again I'm not in any hurry.

**Comment by LADSoft** [comment] 2020-05-20 16:15
@claunia, the main problem with this compiler is it has got to keep things in a format that can be passed to unmanaged code, that is the primary complication for strings.    But with some effort a lot could be done with conversions to make at least string constants more C# friendly.

There was issue #28 that asked basically for a 'safe' version of the runtime (compile the runtime as managed code).    But a lot more needs to be done to make that a reality.

@GitMensch, @claunia I'm not sure what 'legal C#' means.    If you mean code the C# compiler can compile when not in unsafe mode, that is a not a trivial task because it requires the C runtime to be compiled as managed code.    Problem being as I recall some of the constructs needed to support the PInvokes down to unmanaged code are considered 'unsafe' by the C# compiler.   (the unmanaged code typically being msvcrt.dll at this point)

But maybe you mean something other than 'safe'  code.    If so let me know and I'll see if it is possible in the short term.

Anyway since you don't mind waiting I'll find a future milestone to put this in.    I'm fine with doing it just cannot do it immediately!

**Comment by claunia** [comment] 2020-05-20 16:17
@LADSoft I mean something different than "unsafe". I got szip and beha to compile (I had to use stubs for unix functions but I dont care that can be postprocessed), then passed the output to JetBrains and it added comments about some thing then copied back to Rider there it complained that was not valid C#. I will paste the decompiled output that fails later today.

**Comment by claunia** [comment] 2020-05-20 18:18
So this is the output from Jetbrains DotPeek:
```csharp
  public static unsafe void ac_out(ushort low, ushort high, ushort tot)
  {
    uint num = (uint) Module.L_0_d21cc7f7 - (uint) Module.L_1_d21cc7f7 + 1U;
    Module.L_0_d21cc7f7 = (ushort) ((uint) (ushort) (num * (uint) high / (uint) tot - 1U) + (uint) Module.L_1_d21cc7f7);
    Module.L_1_d21cc7f7 += (ushort) (num * (uint) low / (uint) tot);
    if ((((int) Module.L_0_d21cc7f7 ^ (int) Module.L_1_d21cc7f7) & 32768) == 0)
    {
      Module.L_5_d21cc7f7 <<= 1;
      if (((int) Module.L_1_d21cc7f7 & 32768) != 0)
        Module.L_5_d21cc7f7 |= (short) 1;
      if (((int) Module.L_5_d21cc7f7 & 256) != 0)
      {
        // ISSUE: cast to a reference type
        // ISSUE: explicit reference operation
        ^(sbyte&) ((IntPtr) &Module.ob + Module.obl) = (sbyte) (byte) ((uint) Module.L_5_d21cc7f7 & (uint) byte.MaxValue);
        ++Module.obl;
        if (Module.obl == 8192)
          Module.bwrite();
        Module.L_5_d21cc7f7 = (short) 1;
      }
      while (Module.L_3_d21cc7f7 != (short) 0)
      {
        --Module.L_3_d21cc7f7;
        Module.L_5_d21cc7f7 <<= 1;
        if (((int) ~Module.L_1_d21cc7f7 & 32768) != 0)
          Module.L_5_d21cc7f7 |= (short) 1;
        if (((int) Module.L_5_d21cc7f7 & 256) != 0)
        {
          // ISSUE: cast to a reference type
          // ISSUE: explicit reference operation
          ^(sbyte&) ((IntPtr) &Module.ob + Module.obl) = (sbyte) (byte) ((uint) Module.L_5_d21cc7f7 & (uint) byte.MaxValue);
          ++Module.obl;
          if (Module.obl == 8192)
            Module.bwrite();
          Module.L_5_d21cc7f7 = (short) 1;
        }
      }
      Module.L_1_d21cc7f7 <<= 1;
      Module.L_0_d21cc7f7 <<= 1;
      for (Module.L_0_d21cc7f7 |= (ushort) 1; (((int) Module.L_0_d21cc7f7 ^ (int) Module.L_1_d21cc7f7) & 32768) == 0; Module.L_0_d21cc7f7 |= (ushort) 1)
      {
        Module.L_5_d21cc7f7 <<= 1;
        if (((int) Module.L_1_d21cc7f7 & 32768) != 0)
          Module.L_5_d21cc7f7 |= (short) 1;
        if (((int) Module.L_5_d21cc7f7 & 256) != 0)
        {
          // ISSUE: cast to a reference type
          // ISSUE: explicit reference operation
          ^(sbyte&) ((IntPtr) &Module.ob + Module.obl) = (sbyte) (byte) ((uint) Module.L_5_d21cc7f7 & (uint) byte.MaxValue);
          ++Module.obl;
          if (Module.obl == 8192)
            Module.bwrite();
          Module.L_5_d21cc7f7 = (short) 1;
        }
        Module.L_1_d21cc7f7 <<= 1;
        Module.L_0_d21cc7f7 <<= 1;
      }
    }
    for (; ((int) Module.L_1_d21cc7f7 & 16384) != 0 && ((int) Module.L_0_d21cc7f7 & 16384) == 0; Module.L_0_d21cc7f7 |= (ushort) 32769)
    {
      ++Module.L_3_d21cc7f7;
      Module.L_1_d21cc7f7 <<= 1;
      Module.L_1_d21cc7f7 &= (ushort) short.MaxValue;
      Module.L_0_d21cc7f7 <<= 1;
    }
  }
```

and this is the original code

```c
static U16B h,l,v;
static S16B s;
static S16B gpat,ppat;

#define BLOCKLEN 	8192

#define putbyte(c) {ob[obl++]=(c);if(obl==BLOCKLEN)bwrite();}

#define putbit(b) 	{ ppat<<=1;				\
			  if (b) ppat|=1;			\
			  if (ppat&0x100) {			\
				putbyte(ppat&0xff);		\
				ppat=1;				\
			  }					\
			}

void ac_out(U16B low, U16B high, U16B tot) {
    
    register U32B r;
    
    r=(U32B)(h-l)+1;
    h=(U16B)(r*high/tot-1)+l;
    l+=(U16B)(r*low/tot);
    if (!((h^l)&0x8000)) {
	putbit(l&0x8000);
	while(s) {
	    --s;
	    putbit(~l&0x8000);
	}
	l<<=1;
	h<<=1;
	h|=1;
	while (!((h^l)&0x8000)) {
	    putbit(l&0x8000);
	    l<<=1;
	    h<<=1;
	    h|=1;
	}
    }
    while ((l&0x4000)&&!(h&0x4000)) {
	++s;
	l<<=1;
	l&=0x7fff;
	h<<=1;
	h|=0x8001;
    }
}
```

Comments were added by DotPeek itself, and those lines are precisely, the ones that cannot be compiled back. This is what matters, everything else is a nice to have, but can be fixed in preprocessing.

Interestingly enough it always happens in the defined macros.

Sidenote: in the future it would be nice to generate a PDB file, this would allow DotPeek to show proper variable names instead of L_1_whatever? Even comments can be get back from PDB files.

**Comment by claunia** [comment] 2020-05-20 18:20
Oh, full source code is at http://www.claunia.com/files/beha10s.zip
It expects to be compiled on BeOS so some POSIX functions need to be stubbed to link.

**Comment by claunia** [comment] 2020-05-20 18:32
This is a manual conversion from C to C# of that function (I do not expect it to be the same, I'm not crazy, but I think is an example of maybe just convert code macros into methods, if that's at all possible)

```csharp
        static ushort h, l, v;
        static short s;
        static short gpat, ppat;

        const int BLOCKLEN = 8192;

        static byte[] ob;
        static int obl;

        static void putbyte(ushort c)
        {
            ob[obl++] = (byte) (c);
            if (obl == BLOCKLEN) bwrite();
        }

        static void putbit(ushort b)
        {
            ppat <<= 1;
            if (b != 0) ppat |= 1;
            if ((ppat & 0x100) != 0)
            {
                putbyte((ushort) (ppat & 0xff));
                ppat = 1;
            }
        }

        void ac_out(ushort low, ushort high, ushort tot)
        {
            uint r;

            r = (uint) (h - l) + 1;
            h = (ushort) ((r * high / tot - 1) + l);
            l += (ushort) (r * low / tot);
            if (!(((h ^ l) & 0x8000) != 0))
            {
                putbit((ushort) (l & 0x8000));
                while (s != 0)
                {
                    --s;
                    putbit((ushort) (~l & 0x8000));
                }

                l <<= 1;
                h <<= 1;
                h |= 1;
                while (!(((h ^ l) & 0x8000) != 0))
                {
                    putbit((ushort) (l & 0x8000));
                    l <<= 1;
                    h <<= 1;
                    h |= 1;
                }
            }

            while (((l & 0x4000) != 0) && !((h & 0x4000) != 0))
            {
                ++s;
                l <<= 1;
                l &= 0x7fff;
                h <<= 1;
                h |= 0x8001;
            }
        }
```

**Comment by LADSoft** [comment] 2020-05-20 22:20
@claunia ok let me see what I can do about the problems DotPeek references.   Probably there is another way to do what is being done there...    I'll also see what I can do about using more reasonable names than the L_XXX stuff occil is doing.    When I designed this I wasn't thinking in terms of human consumption but rather code generation.

I don't think I can turn macros into functions in the short term, but can look at that in the longer term if you would like...

**Comment by GitMensch** [comment] 2020-05-20 22:42
> I don't think I can turn macros into functions in the short term, but can look at that in the longer term if you would like...

I'd like that, but "obviously" you'd have to create one for each different argument type (given a sample that uses int and char...). Please create a FR issue for this that may be done "sometime in the future, possibly 2021 or later".

"Using more reasonable names" would be nice, too and something that may be done additional to the PDB generation which @claunia asked for and is a general issue that already exists.

In any case I suggest that @claunia or @LADSoft renames this issue as it isn't about generating C# instead of IL any more, is it?

**Comment by LADSoft** [comment] 2020-05-21 00:29
@gitmensch thanks I forgot to comment on the PDB issue.   We have an issue for PDBs already #252, which is to get done in milestone5.   I had offered to fix the names in the il code though, so that dotpeek will at least give readable text.

I'm undecided whether to change the name of this issue, since I'm planning on doing what the title says at a later date we'll still need a similar one.   I might just make two new issues for the things we talked about here and update the PDB issue with the new info as well.

**Comment by LADSoft** [comment] 2020-05-21 00:32
@claunia I had to bracket the new types in types.h with 
#define MY_UNSIGNED_TYPES
... new types
#endif

because it broke the build sigh.

Also you can make szip compile with occil by adding 
#define setmode _setmode
and removing your stub.

**Comment by chuggafan** [comment] 2020-05-21 12:41
So now with the new issue title the one problem I see with performing this change is that even for regularly compiled C# dotPeek has major problems with creating re-compilable binaries (particularly with extension methods IIRC). Even though dotPeek is the best C# decompiler I know of, it still struggles with not outputting clear names for everything. So I suggest that we get it "GOOD ENOUGH TO READ" (e.g. macros are replaced with constexpr -> get compiled to runtime functions).

While I agree that it does make sense to make it so that dotPeek can decompile our code via these methods, I do not think (all-in-all considering how dotPeek is closed source and we won't be able to figure out exactly why certain names are just unicode spaces), it is worth it to spend a great deal of time on the name issue.

My 2c on my previous usages of dotPeek from back when the C# runtime was closed source instead of open and I was mucking around trying to figure out what went on internally everywhere.

**Comment by LADSoft** [comment] 2020-05-21 16:31
@chuggafan, Based on the data available in the IL I don't know if it would be possible to fix function argument names but it probably wouldn't be possible to fix function local variable names.    At least unless DotPeek handles reading the PDB.   The PDB is being left for another day though...   But I think it may be worth it to at least shoot for fixing the static names...   the ones that start L_ and have a long string of numbers on the end were probably generated by the compiler so I have control over them.    That at least gives *something* more than what we've got.

**Comment by chuggafan** [comment] 2020-05-21 17:10
Yhea, that's a reasonable goal, the problem I was remembering happened with the actual function names themselves, not even their arguments. I think it had to do with constructors or something of the sort, but it's been about ~3 years since I've used dotpeek heavily and a lot could have changed in the meantime for that.

**Comment by LADSoft** [comment] 2020-05-21 19:36
yeah the static and dynamic constructors are named wierdly so the IL reader can find them, DotPeek would have to figure out what class they go with to figure out the real names....   the static constructors are mostly invisible in C# so they don't even have a name...   Dot peek would have to do real work to associate variables with their static construction....

**Comment by claunia** [comment] 2020-05-23 02:02
DotPeek certainly can read the PDBs.

**Comment by LADSoft** [comment] 2020-05-24 01:21
cool.

**Comment by LADSoft** [comment] 2020-05-24 21:59
I've got something workable, my working version of occil generates code csc can recompile.   But a small amount of search and replace has to be used on the dotpeek output to get rid of IntPtr and UIntPtr casts...   I don't know a way to get dotpeek to elide them.

The big change was pointers sometimes have to be pinned...   but there are a variety of smaller changes that were made to clean up code generation.

Right now I'm trying to get szip to run properly when recompiled with csc.   I think it is almost there though...

**Comment by LADSoft** [comment] 2020-05-27 13:41
had to rework since not enough stuff was being accessed with 'fixed' modifier.   There are problems with passing things down via pinvoke at the moment...   which got me thinking maybe I should digress again and at least fix string constants to be readable...

Meanwhile there are a couple of bugs in DotPeek that I can't work around....  will probably try to find a way to report them when I get this done...

**Comment by GitMensch** [comment] 2020-05-27 14:30
Before wasting time on a proprietary decompiler I suggest to go with something like https://github.com/icsharpcode/ILSpy

**Comment by LADSoft** [comment] 2020-05-27 16:46
@GitMensch I should clarify the issues with DotPeek are quite minor; a missing cast in one place (even when I explicitly put the cast into the IL code stream)  and in one place it messes up the end of a 'fixed' statement by saying there is a misplaced 'unpin' instruction.    The latter I verified by compiling the decompiled code with CSC then decompiling it again...  same results.    In one case add the cast and in the other remove the offending line of code; both are flagged as invalid by CSC in any case...

My problem right now is figuring out why fprintf doesn't work when compiled from CSC and I don't have any reason to believe that is also a DotPeek bug...  So I don't have much problem continuing with DotPeek. 

I'll run it through ILSPY though too to see what happens :)

**Comment by LADSoft** [comment] 2020-05-28 17:09
i got the compiler to generate code that wouldn't inspire DotPeek to generate intptr references and figured out to specify /platfrom:x86 when compiling the decompiled code with CSC, and szip works halfway - compresses but doesn't decompress.   Tonite I will try this with ILSpy to see if that works any better.

**Comment by LADSoft** [comment] 2020-05-29 00:21
the decompress problem was due to another bug in DotPeek (which coincidentally is also in ILSPY) but I worked around it by pulling out a compiler optimization that isn't really needed for MSIL.   OCC does things that CSharp compilers would never do, apparently...

ILSPY also has problems, the two immediately obvious are it doesn't support 'fixed' statements, which are essential for this.   And it doesn't coalesce array references back into array references either, which is another source of IntPtr references...

I reported bugs both to the DotPeek team and the ILSPY team.

Tomorrow I'm going to see about adding support for using MSIL strings to make the code more readable then we can close this.

**Comment by GitMensch** [comment] 2020-05-29 09:08
> the decompress problem was due to another bug in DotPeek (which coincidentally is also in ILSPY) but I worked around it by pulling out a compiler optimization that isn't really needed for MSIL. OCC does things that CSharp compilers would never do, apparently...

Sounds like a feature to keep (possibly with an option to deactivate) not a bug in the OrangeC part, don't you think?

Is the bug part in ILSpy for this also part of https://github.com/icsharpcode/ILSpy/issues/2023 or is it a separate issue?

> Tomorrow I'm going to see about adding support for using MSIL strings to make the code more readable then we can close this.

Sounds reasonable! If you want to challenge ocil and ilspy: Please try something similar with GMP (I agree that this would be a completely different issue ;-)

**Comment by LADSoft** [comment] 2020-05-29 12:18
yeah the problem is that you have to have the fixed statements, for C# to compile the resulting code in a way that will work.   The fact that ILSPY doesn't do that makes it a non-starter...   no point in even trying it with a highly complicated program like that.   OTOH I do intend to try it with my CC386 example in the test suite....   as soon as I get that to work again at all sigh.   I apparently introduced at least four new bugs while working on this...    thank goodness you talked me into making complicated test suites!

I didn't report the other issue though.   I'll see about it later today...

**Comment by claunia** [comment] 2020-05-29 14:00
The amount of progress is amazing!

And using SZIP as an example demonstrated good, I suspected, as compression algorithms are very fragile at the bit level :D

Keep up!

**Comment by LADSoft** [comment] 2020-05-30 17:25
I know people think me fast, but well but I think it is just going way too slow!   Some of my debug sessions seem almost interminable :)

yeah I've historically had problem with compressors,  signed/unsigned shifting and bit operations get really intensive!   then there is all the conversion between bytes and shorts to ints...    a lot of room for the compiler to mess up!   I have a couple of compressors in my test suite for just that reason...   maybe I will add szip to the occil tests, if the licensing will allow.

I got all the bugs worked out that I introduced with the recent changes, and then tried this with a larger program (my old compiler).   some minor issues to be addressed yet I guess.   Right now .Net won't even load the results...   still haven't had a chance to address the string issue yet either.

**Comment by claunia** [comment] 2020-05-30 17:28
I know the feeling, specially when I'm debugging some bug that only appears at half of reading a CD, so minutes just waiting for it to ARRIVE to the point of discord :(

But this feature would just make my needs of porting compression algorithms to C# reduced by several orders of magnitude, and so my gratitude for your efforts are proportional.

**Comment by LADSoft** [comment] 2020-05-31 00:01
sure.   There is a lot of waiting!   Drives me batty!

Today's news is that I got everything working again and then compiled my old compiler with fixed statements...   found more bugs that way.   DotPeek totally bombs on disassembling it though so I can't proceed down that path in terms of testing the disassembly/reassembly.   ILSPY at least loads it although as discussed has issues...   

The other issue I talked about with both DotPeek and ILSPY turned out to be a non-issue on ILSPY.   User Error, as they say...   I've registered a couple of new bugs with the DotPeek people now.   Not holding my breath lol!

I'm going to do more testing then start fixing the strings issue...

**Comment by LADSoft** [comment] 2020-05-31 16:09
@claunia,

so while I was testing I found out that that  occil doesn't compile method pointers in a way that can be decompiled.   Is that something you need immediately?

**Comment by LADSoft** [comment] 2020-06-02 19:38
I added support for strings readable in the decompiled code, although it can't handle figuring out the initialization for arrays of characters, just does strings that are inlined in the code....   I think it will also handle char* initializations at global scope but that will be buried in an initialization function somewhere.   

Two issues left to go.   Gotta clean up the code generation for multidimensional arrays (which will likely turn into single-dimensional arrays with explicit calculations for the indices if I can pull it off at all) and gotta fix the handling of method pointers like I talked about the other day.

**Comment by LADSoft** [comment] 2020-06-07 02:51
ok the multidimensional arrays were kinda easy, then there are method pointers.   Since CSharp can't handle bare CIL in this respect there is a new switch to generate Action or Func references for function pointers.   Somewhat involved since I had to do minimal support for generic types in the dot net library.   

That wraps up the development AFAIK so I'll test some more now.

There are three new switches now, one for pinning, one for using native strings when possible, and one for generating Action/Func references for function pointers.

**Comment by claunia** [comment] 2020-06-09 16:07
Nice!

Is there a binary release I can test? I have a more modern compression algorithm to make it suffer hehe :smile:

**Comment by LADSoft** [comment] 2020-06-10 00:03
it is still a work in progress but I've pushed what I've got.   If it builds you can get it off appveyor.

I added basic documentation to [occil.md](https://github.com/LADSoft/OrangeC/blob/master/doc/occil.md),

Haven't completely vetted the Action/Func stuff but it seemed to at least generate usable code when I tried it on a couple of things.    I haven't fully vetted the multidimensional array thing either but it seemed good in simple tests.   The other stuff should be ok at this point.   I'm working now on fixing an existing bug in the compiler...  in one case it generates good code but as one of my tests indicated it isn't good enough to work around assumptions made by the runtime system.   I have to rework it :)

if you try this on szip bear in mind there are a couple of things that DotPeek gets wrong...   it will be obvious what to do when you try to recompile with CSC.  If you try it on other things I welcome your comments :)

**Comment by LADSoft** [comment] 2020-06-12 00:10
the build mostly went through the other day, just gcc had problems with something I changed.   I think the build going now should fix that...

The 'Action' statements seem to be working nicely.

I fixed a bug in the pinning: arrays of pointers didn't work so well.

Meanwhile I found another problem:   sometimes occil generates 'initblk' instructions and that doesn't play well with the disassembly, it not only generates an issue because C# can't generate those, but it messes up related pinning sequences.   Will look into it soon...

**Comment by LADSoft** [comment] 2020-06-12 00:23
one of my test programs is bzip2...   when I first tried it dotpeek wouldn't even try to disassemble it so I couldn't see problems.   But there are some issues I will also address soon.

**Comment by LADSoft** [comment] 2020-06-15 00:29
There were all sorts of problems with using Action and Func.   So I rewrote using delegates and the code generated by DotPeek is much cleaner.   Although essentially the code had to thunk through an unmanaged subroutine to get it to work the way well enough to be useable.

There are a couple of minor issues left which won't be too hard to address.    The main issue that I don't know what to do with is that all those macros in bzip2 end up putting case statements nested inside a couple of levels of control statements nested inside another case statement inside the switch.   Legal if not somewhat bizarre C, but DotPeek generates labels that are outside the scope of the corresponding gotos for the routine in question...   csc doesn't like it.    I'll see if I can do anything about it when I am less tired 😄

**Comment by LADSoft** [comment] 2020-06-17 17:05
There was a bug where the versions of occil compiled with occ didn't work which I addressed well enough to get it working again.

I think we need an option to auto-initialize uninitialized local variables...    sometimes C# can't tell a variable gets a value even though the set couldn't be bypassed based on the logic flow.   Which is another source of errors...

The only other thing left on the list at this point is whether anything can be done about the out of scope gotos generated for bzip2...

**Comment by LADSoft** [comment] 2020-06-18 20:36
I've taken this about as far as I can.    There is nothing I can do about the switch/case problem in general....   bzip2 just takes it too far for csc to be able to handle.   

One option is to rewrite bzip2 before compiling with occil...   there are two immediate ideas that come to mind.    First get rid of the switch/case entirely.    But that is at the expense of not being able to decompress on the fly.   The other idea is a little harder but I think it would work:   remove the while and for loops that are the problem and replace them with new states in the state machine.   The code would be a little less manageable from the perspective of maintainance but CSC should be able to handle it...

**Comment by dgrunwald** [comment] 2020-06-23 23:44
Feel free to create more ILSpy issues for any bugs you find.

In general I think it's better to fix the decompiler than to make your compiler emit certain code patterns.
E.g. the fixed statements wouldn't be necessary if ILSpy had support for adding [Unsafe.AsPointer](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.unsafe.aspointer) calls where appropriate. (though I'm not 100% clear on whether .NET guarantees that the GC won't move static variables -- these fixed statements might actually be necessary for correctness?)

Function pointers are already tracked by icsharpcode/ILSpy#1963 and given that there's a [proposal for C# 9](https://github.com/dotnet/csharplang/blob/master/proposals/function-pointers.md) floating around, this might actually get implemented in the near future.

**Comment by LADSoft** [comment] 2020-06-24 11:54
I kinda agree that it is nicer getting the decompiler working but getting the DotPeek people to fix things istaking forever so I kinda punted.

I really didn't know what to do about the issue where the compiler returns a pointer to a string, and the expectation once it returns is the string will be fixed, but the fixed statement has gone out of scope.

If you think you can get by without the fixed statements that would be nice...   I'm not sure either though about static variables.   CSC says they are members of a 'reference' class and that implies they could be moved...   honestly though I've never actually seen them move in programs I've run.

But I ended up turning function pointers into delegates to make dotpeek happy.    

When I get a chance I will try ilspy with my latest code and see how it fares :)

**Comment by dgrunwald** [comment] 2020-06-24 23:08
@LADSoft With my improvements on icsharpcode/ILSpy#2045 I can successfully decompile+recompile the assembly you provided.

For your compiler, I suggest the following changes to make the decompiled code a bit prettier:
 * Ensure you use the correct type for pinned variables. Currently it looks like pinning `&mod.whatmod` uses the type of `mod` when it should use the type of `whatmod`. DotPeek was ignoring the pinned variable type; ILSpy is using it.
 * Insert a `conv.i` before the multiplication in pointer arithmetic. ILSpy expects pointer arithmetic to happen with native-sized integers. 32-bit pointer arithmetic won't decompile to pretty code as it has different overflow semantics on 64-bit runtimes. (compare with the IL code emitted for pointer arithmetic by the C# compiler)

Please open new ILSpy issues for any additional bugs you find. Using new IL code patterns that the decompiler has never seen before is always a good way to find bugs :)

In general between the `System.Runtime.CompilerServices.Unsafe` and the upcoming C# 9 features, there shouldn't be much IL code that cannot be represented accurately in C#. Not all of those new features are supported in the decompiler yet; but I can prioritize those you need.

**Comment by LADSoft** [comment] 2020-10-17 06:42
I started working on this again...   fixed some stuff but ran into an issue with ILSPY that I opened in icsharpcode/ILSpy#2189

**Comment by LADSoft** [comment] 2020-11-08 06:48
from the comments left in icsharpcode/ILSpy#2189:

The IL is a bit weird:

```
	IL_0000: ldsflda valuetype __anontype_b76acefe_0002 '<Module>'::mod /* 04000036 */
	IL_0005: ldflda valuetype __anontype_b76acefe_0001_array_32768 __anontype_b76acefe_0002::mtfhist /* 04000054 */
	IL_000a: conv.u
	IL_000b: stloc.1

```
ldflda produces a managed reference, conv.u converts it to an unmanaged pointer; then stloc.1 implicitly converts it back to a managed reference (since the local is of type valuetype __anontype_b76acefe_0001& pinned).

Without the conv.u, ILSpy outputs valid code using Unsafe.As<>.

**Comment by LADSoft** [comment] 2020-11-10 21:36
opened icsharpcode/ILSpy#2215 with a query about arrays of pointers to structures...

**Closed** 2023-08-10 17:06 UTC
